---
name: Test Workflow

on:
  workflow_call:

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: ⬇ Checkout repo
        uses: actions/checkout@v3

      - name: 🌱 Setup environment
        run: |
          touch .env
          echo "VITE_FIREBASE_PROJECT_ID=${{secrets.VITE_FIREBASE_PROJECT_ID}}" >> .env

      - name: 🧪 Cypress run
        run: docker-compose -f docker-compose.yml -f docker-compose.cypress.yml up --abort-on-container-exit --exit-code-from cypress

      - name: 📷 Upload Screenshots
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: e2e/cypress/screenshots

      - name: 🎥 Upload Videos
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-videos
          path: e2e/cypress/videos
