name: On Pull Request

on: pull_request

permissions:
  pull-requests: write
  contents: write
  actions: read
  security-events: write

jobs:
  dependabot:
    uses: ./.github/workflows/99-auto-merge.yml

  codeql:
    uses: ./.github/workflows/99-codeql-analysis.yml

  dependency-review:
    uses: ./.github/workflows/99-dependency-review.yml

  labeler:
    uses: ./.github/workflows/99-labeler.yml

  init:
    uses: ./.github/workflows/00-init.yml

  build:
    uses: ./.github/workflows/01-build.yml
    needs: [init]
    secrets: inherit

  preview:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }} && ${{ github.actor != 'dependabot[bot]' }}
    uses: ./.github/workflows/02-hosting.yml
    needs: [build]
    secrets: inherit
