name: Push to main
on:
  push:
    branches:
      - main
jobs:
  init:
    uses: ./.github/workflows/00-init.yml

  build:
    uses: ./.github/workflows/01-build.yml
    needs: [ init ]
    secrets: inherit

  deploy:
    uses: ./.github/workflows/03-hosting.yml
    with:
      channelId: live
    needs: [ build ]
    secrets: inherit
