name: Push to main
on:
  push:
    branches:
      - main
jobs:
  init:
    uses: ./.github/workflows/00-init.yml

  test:
    uses: ./.github/workflows/00-test.yml
    secrets: inherit

  build:
    uses: ./.github/workflows/01-build.yml
    needs: [init]
    secrets: inherit

  deploy:
    uses: ./.github/workflows/02-hosting.yml
    with:
      channelId: live
    needs: [test, build]
    secrets: inherit
